- name: Enable Foreman repositories
  ansible.builtin.apt_repository:
    repo: "{{ repo }}"
    filename: "{{ foreman_repo_filename }}"
    update_cache: true
  loop_control:
    loop_var: repo
  loop: "{{ foreman_repos }}"

- name: Install Foreman installer
  ansible.builtin.apt:
    name: foreman-installer
    state: present

- name: Run Foreman installer
  command: foreman-installer
  register: result
  failed_when: register.rc != 0
